server {
      listen  8802 default_server;
      lua_need_request_body on;
      client_max_body_size 5M;
      client_body_buffer_size 5M;
      location /data/v1 {
        content_by_lua_file /opt/app/collect-app/lua/collect-app.lua;
        # 容器中禁用access_log
	      access_log off;
	      #access_log  logs/collect-app-lua.access.log  main;
      }
}
